import streamlit as st
import datetime
st.header("STUDENT REGISTRATION FORM")
my_form = st.form(key = "form-1")
fname =  my_form.text_input("Student First Name:")
lname =  my_form.text_input("Student Last Name:")
email = my_form.text_input("Student email id:")
mobile = my_form.text_input("Student mobile number:")
gender = my_form.radio('Gender',('male','female'))
age = my_form.slider('AGE',1,100)
dob = my_form.date_input("Enter date of birth:",min_value=datetime.date(1990,1,1))
addr = my_form.text_area("Enter your address")
resume = my_form.file_uploader("Upload your Resume:")
my_form._form_submit_button("Submit")
st.write("First name: ",fname)
st.write("Last name: ",lname)
st.write("Email: ",email)
st.write("Mobile number:",mobile)
st.write("Gender:",gender)
st.write("Age:",age)
st.write("DOB: ",dob)
st.write("Address: ",addr)
st.write("Resume:",resume)